### ISSUE TITLE
Debug without breakpoints set

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/artik-ide#146]
When I start the debugger without breakpoints set there is a "loading.." popup window that will not go away.

![issue2](https://cloud.githubusercontent.com/assets/20580888/18213320/3f91e678-710d-11e6-842a-9c4e31d96682.gif)

When I start debugger with breakpoints debugger works as expected. However if I remove all breakpoints there is a "loading.." popup window that will not go away.

![issue1](https://cloud.githubusercontent.com/assets/20580888/18213312/38d2f6ec-710d-11e6-93d2-cd56812f41cd.gif)

I would expect the debugger to work without breakpoints set initially or when all breakpoints are removed when application is already running. 
- [ ] Remove "loading..." popup and added process running indicator in the debug area with text or animated icon.
- [ ] Add ability to load breakpoints in running process.

**Comment by JamesDrummond** [comment]
We need to see if there is a way to remove the "loading..." popup and add a status indicator or running icon somewhere else, maybe in debug window, to notify user that program is running.

Endless loop programs will often be used for Artik applications such as controllers, robotics etc. We need a way to load breakpoints on a running process. The following is how I am able to do this manually. It involves sending an SIGINT signal to the running program on the Artik device. The gdbserver will detect this signal and pause the execution of the program. Once paused a breakpoint can be added and the program can continue.

1. Run `gdbserver :1234 /root/projects/artik-blink-led/a.out` in a Artik device terminal. This will create two processes one for the gdbserver and one for the actual program.
2. Run `gdb /projects/artik-blink-led/a.out` in a ws terminal. Then `target remote <artik-ip>:1234` and `continue`. This will cause the gdb to be stuck in the running process unable to create new break points.
3. Run `kill -s SIGINT <program-pid>` in another Artik device terminal. This will send sigint signal to the process of a.out(NOT gdbserver). Gdbservers listen for signals sent to an attached process. When it catches SIGINT signal it pauses the process. Take note that the SIGINT signal will never terminate the process only pause it is needed.
4. Go back to ws terminal in step 2 and you will see that the gdb in not stuck and you can now enter a breakpoint `break 74`. Once this break point is entered issue `continue` in gdb, process will continue running and pause/break at line 74.

![issue](https://cloud.githubusercontent.com/assets/20580888/18217986/785fa996-7125-11e6-9793-91fcf8c97908.gif)

I think we need a way to capture the process PID when it is created. The SIGINT can be issued everytime a new breakpoint is added as it will never terminate the process and can even be used when the process is already paused at a breakpoint.

**Comment by bmicklea** [comment]
I think we need to handle the following use case, especially for junior developers who may not be familiar with debugger behavior. Junior developers are a primary target for the ARTIK IDE.

*Use Case*: A user starts the GDB debugger with no breakpoints set, then realizes that they need one. So the user clicks a new breakpoint in the editor with the debugger working and is confused because the new breakpoint doesn't work.

*Today*: because the debugger is running, GDB doesn't register the new breakpoint. The GDB server needs to be suspended and resumed for the breakpoint to register. This may be obvious to experienced developers, but is confusing for junior developers.

*Fix*: the user should receive a notification: "Suspend, then resume the debugger to activate new breakpoints." 
the  and a developer adds a breakpoint it won't be registered in GDB until the GDB server is suspended and resumed. When

**Comment by bmicklea** [comment]
@RomanNikitenko is this still in progress?

**Comment by bmicklea** [comment]
Fixed

**Comment by RomanNikitenko** [comment]
Pull request in Che project https://github.com/eclipse/che/pull/3274
