### ISSUE TITLE
ARTIK IDE Launching problems on Win7

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#176]
**Description of problem:**
Cannot enter ARTIK IDE's created workspace from browser

**ARTIK IDE version:** 
ARTIK IDE binaries: samsung-artik-ide-nightly (2016/10/14)
Docker version: 1.12.0
Java version: 1.8.0_101
Environment details: **Window 7** + Docker toolbox + JDK
Browser:Chrome

**Steps to Reproduce:**
1. Open the win7's cmd console
2. $cd {artik-ide-binaries-path}\bin
3. $che run
log shows success.
![run_artik_ide](https://cloud.githubusercontent.com/assets/20897963/19503684/e67c5028-95e7-11e6-9ba1-58e71ecd8dc3.PNG)
4. Open the localhost:8080 in Chrome; create a workspace; Enter the created workspace
error msg: cannot loal project type
![ide_cannot_load_project_tab](https://cloud.githubusercontent.com/assets/20897963/19503827/ced3284c-95e8-11e6-9ff3-589d0a7d809b.PNG)

error msg: some error happened with terminal WebSocket connection.
![connection_failed_with_terminal](https://cloud.githubusercontent.com/assets/20897963/19504147/9e30569a-95ea-11e6-8812-72b361d42846.PNG)

@TylerJewell @eivantsov Could you give me the suggestions? or the best practice of IDE lauching on Win7.  Thanks a lot~

**Comment by ddementieva** [comment]
@laralijuan Are there any errors in the browser dev console? 

Can you send a screenshot with browser dev console opened?

**Comment by TylerJewell** [comment]
@laralijuan - this issue means that your workspace and your che-server are able to communicate with each other.  However, this particular error means that the browser is unable to reach the workspace itself.  This is due to a configuration issue, for which you can set certain che.properties to overcome.  For the sorts of things that you can reconfigure to tell the browser how to connect to a workspace, we have the middle of this table.

https://eclipse-che.readme.io/v5.0/docs/networking#connectivity

These sorts of issues happen when you are setting up che on a VM, or when you have your browser, che server, or workspaces on different locations, which are doing here on windows 7.

**Comment by bmicklea** [comment]
Closing older issues, if this is still a problem please reopen.
